apiVersion: v1
kind: Service
metadata:
  name: wordpress-service
  namespace: wordpress
spec:
  type: NodePort
  selector:
    # same name of pod, it needs to match in order the service to select the good pod
    app: wordpress
  ports:
    - protocol: TCP
      # Service port, it common to use the targetPort as service port
      port: 80
      # Container port inside Pod, the service forwards the request to targetPort
      targetPort: 80
      # nodePort exposes the service on each Node's IP at static port range: 30000-32767 
      nodePort: 30100
