apiVersion: v1
kind: Secret
metadata:
  name: wordpress-secret
  namespace: wordpress
type: Opaque
data:
  mysql_root_password: c29tZXdvcmRwcmVzcw==
  mysql_password: d29yZHByZXNz
  wordpress_db_password: d29yZHByZXNz